# Generated by Django 5.1.2 on 2024-11-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auther_id',
            new_name='author',
        ),
    ]
