# Generated by Django 5.1.2 on 2024-10-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
