# Generated by Django 4.2.16 on 2024-11-12 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_block_user_id_blocks_blocked_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_author",
                to="app.user",
            ),
        ),
    ]
